#include "main.h"

int main() {
	// PLL = RCC
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;
	GPIOG->MODER |= GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0;
	GPIOG->BSRR |= GPIO_BSRR_BS13 | GPIO_BSRR_BS14;


	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	// GPIOA->MODER &= ~(GPIO_MODER_MODER0_0 | GPIO_MODER_MODER0_1);


	while(1) {
		if((GPIOA->IDR & GPIO_IDR_ID0) != 0) {
			GPIOG->BSRR |= GPIO_BSRR_BS13 | GPIO_BSRR_BS14;
		} else {
			GPIOG->BSRR |= GPIO_BSRR_BR13 | GPIO_BSRR_BR14;
		}
	}
}

